test: Use build image with golang 1.25
golang 1.24 is no longer supported by the go team, and we have some PRs
which need a newer golang version https://github.com/crc-org/macadam/pull/356
They currently fail with:
```
[1/2] STEP 7/7: RUN GOARCH=${ARCH} GOOS=${OS} make build_e2e     && make bin/macadam-${OS}-${ARCH}
GOOS=windows GOARCH=amd64 go test -v ./test/e2e/ -tags "remote containers_image_openpgp exclude_graphdriver_btrfs btrfs_noversion" -ldflags="-X github.com/crc-org/macadam/pkg/cmdline.gitVersion=06c8c4e -X go.podman.io/common/pkg/config.additionalHelperBinariesDir=" -c -o bin/windows-amd64/e2e.test
go: go.mod requires go >= 1.25.0 (running go 1.24.13; GOTOOLCHAIN=local)
make: *** [Makefile:114: build_e2e] Error 1
Error: building at STEP "RUN GOARCH=${ARCH} GOOS=${OS} make build_e2e     && make bin/macadam-${OS}-${ARCH}": while running runtime: exit status 2
make: *** [Makefile:135: containerized_e2e] Error 2
```